jobs:
# This file contains jobs for an automated CI/CD workflow using Shippable
# Pipelines

################################

# add pipeline workflow for Sock Shop FRONT-END component

# manifest gen
  - name: man-front-end
    type: manifest
    steps:
      - IN: img-front-end
      - IN: img-opts-front-end-test
      - TASK: managed

# TEST deployment to Amazon ECS
  - name: yourName-ecs-deploy-test-front-end
    type: deploy
    steps:
      - IN: man-front-end
      - IN: params-front-end-test
      - IN: trigger-front-end-test
      - IN: cluster-demo-ecs
      - IN: alb-front-end-test
        applyTo:
          - manifest: man-front-end
            image: img-front-end
            port: 40000
      - TASK: managed

# # Create release for PROD
#   - name: release-front-end
#     type: release
#     steps:
#       - IN: ver-front-end
#         switch: off
#       - IN: ecs-deploy-test-front-end
#         switch: off
#       - IN: trigger-front-end-release
#       - TASK:   managed
#         bump: patch

# move this block to separate repo to limit PROD deployment to different users
# PROD deployment to Amazon ECS
  - name: yourName-ecs-deploy-prod-front-end
    type: deploy
    steps:
      - IN: yourName-ecs-deploy-test-front-end
        switch: off
      # - IN: release-front-end
      #   switch: off
      - IN: img-opts-front-end-prod
      - IN: params-front-end-prod
      - IN: replicas-front-end-prod
      - IN: trigger-front-end-prod
      - IN: alb-front-end-prod
        applyTo:
          - manifest: man-front-end
            image: img-front-end
            port: 50000
      - IN: cluster-demo-ecs
      - TASK: managed

################################

# pipeline to create, update and delete infrastructure using CloudFormation

# Shell script infrastructure deployment to AWS
  - name: cfCreateStack
    type: runSh
    steps:
      - IN: repo-cfScripts
      - IN: params-cfScripts
      - IN: integration-aws
      - TASK:
        - script: . /build/IN/repo-cfScripts/gitRepo/deploy/aws-ecs-shippable/create-stack.sh repo-cfScripts params-cfScripts integration-aws
      - on_success:
        - echo "stack created successfully"
      - on_failure:
        - echo "stack not created - error encountered"

# Shell script infrastructure deployment to AWS
  - name: cfUpdateStack
    type: runSh
    steps:
      - IN: cfCreateStack
        switch: off
      - IN: repo-cfScripts
        switch: off
      - IN: params-cfScripts
      - IN: integration-aws
      - TASK:
        - script: . /build/IN/repo-cfScripts/gitRepo/deploy/aws-ecs-shippable/update-stack.sh repo-cfScripts params-cfScripts integration-aws
      - on_success:
        - echo "stack updated successfully"
      - on_failure:
        - echo "stack not updated - error encountered"

# Shell script infrastructure deployment to AWS
  - name: cfDeleteStack
    type: runSh
    steps:
      - IN: cfUpdateStack
        switch: off
      - IN: repo-cfScripts
        switch: off
      - IN: params-cfScripts
      - IN: integration-aws
      - TASK:
        - script: . /build/IN/repo-cfScripts/gitRepo/deploy/aws-ecs-shippable/delete-stack.sh repo-cfScripts params-cfScripts integration-aws
      - on_success:
        - echo "stack deleted successfully"
      - on_failure:
        - echo "stack not deleted - error encountered"
